systemcalc_test: add test for MPPTs with load output
This should fail now, since systemcalc only takes the current coming out of
the battery terminals on an MPPT into account. Instead of battery AND load
terminals.

https://github.com/victronenergy/venus/issues/233

make tests shows:

======================================================================
FAIL: test_solar_charger_with_load_output (systemcalc_test.TestSystemCalc)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/matthijs/dev/dbus-systemcalc-py/tests/systemcalc_test.py", line 361, in test_solar_charger_with_load_output
    '/Dc/Pv/Power': 12 * (8 + 5)})
  File "/home/matthijs/dev/dbus-systemcalc-py/tests/base.py", line 76, in _check_values
    self.assertTrue(ok, msg)
AssertionError: /Dc/Pv/Power:	156	96
/Dc/System/Power:	None	None